//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageSales.Data.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GarageSalesContext : DbContext
    {
        public GarageSalesContext()
            : base("name=GarageSalesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<ImageType> ImageTypes { get; set; }
        public virtual DbSet<ItemAdminComment> ItemAdminComments { get; set; }
        public virtual DbSet<ItemLink> ItemLinks { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<LinkType> LinkTypes { get; set; }
    }
}
