//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageSales.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int image_id { get; set; }
        public int item_id { get; set; }
        public int image_type { get; set; }
        public string image_name { get; set; }
    
        public virtual ImageType ImageType { get; set; }
        public virtual Item Item { get; set; }
    }
}
